---

- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
    cache_valid_time: 36000

- name: add install deb.torproject.org signing key
  apt_key:
    keyserver: keys.gnupg.net
    id: 'A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89'

- name: add deb repo "{{ tor_repo }}"
  apt_repository:
    state: present
    repo: "deb {{ tor_repo }} {{ ansible_lsb.codename }} main"

- name: add Debian testing repo
  apt_repository:
    state: present
    repo: "deb https://deb.debian.org/debian testing main"
  when: install_deb_pkg

- name: termplate testing preferences apt pinning file
  template:
    src: testing.pref.j2
    dest: /etc/apt/preferences.d/testing.pref
  when: install_deb_pkg

- name: install tor and sbws dependencies
  apt:
    name: [ deb.torproject.org-keyring, tor, tor-geoipdb, sbws]
    state: latest
    cache_valid_time: 36000
    install_recommends: no
  when: install_deb_pkg

- name: install tor and sbws dependencies
  apt:
    # acl package is needed to install sbws as user
    name: [ deb.torproject.org-keyring, tor, tor-geoipdb, python3, virtualenv, python-setuptools, python-pip, acl]
    state: latest
    cache_valid_time: 36000
    install_recommends: no
  when: not install_deb_pkg

- name: check that sbws package is not installed, we install it via pip
  apt:
    name: sbws
    state: absent
  when: not install_deb_pkg

- name: upgrade pip
  pip: name=pip state=latest
  when: not install_deb_pkg
